# Welcome to Serverless!
app: blog-service
# org: tuanhung
service: blog-service
frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:DescribeTable
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "*"
  stage: dev
  region: ap-southeast-1
    

functions:
  blogCreate:
    handler: src/controller.blogCreate
    events:
        - httpApi:
            path: /blog
            method: post
  blogList:
    handler: src/controller.blogList
    events:
        - httpApi:
            path: /blog
            method: get
  blogDetail:
    handler: src/controller.blogDetail
    events:
        - httpApi:
            path: /blog/{id}
            method: get
  blogUpdate:
    handler: src/controller.blogUpdate
    events:
        - httpApi:
            path: /blog/{id}
            method: put
  blogDelete:
    handler: src/controller.blogDelete
    events:
      - httpApi:
          path: /blog/{id}
          method: delete

plugins:
  - serverless-plugin-typescript
  - serverless-offline
